---
title: "_Datasets_ | Miscellaneous"
author: "Tiernan Martin, [Futurewise](http://www.futurewisewa.org/)"
df_print: tibble
output:
  html_notebook: default
  pdf_document:
    keep_tex: yes
subtitle: Communities of Opportunity Displacement Risk Assessment
always_allow_html: yes
---

###Seattle Boundary

```{r, echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(rgdal)
library(sp)
library(rgeos)
library(miscgis)
library(tigris)
library(leaflet)
library(ggthemes)

if(!file.exists("./1_raw/seattle.gpkg")){
        tigris::places(state = "WA") %>%
        tigris::filter_place(place = "Seattle") %>%
        spTransform(CRSobj = crs_proj) %>% 
        writeOGR(dsn = "./1_raw/seattle.gpkg",
                 layer = "seattle", driver = "GPKG", verbose = FALSE, 
                 overwrite_layer = TRUE)
}

sea <- readOGR(dsn = "./1_raw/seattle.gpkg",layer = "seattle",verbose = FALSE)

green <- miscgis::miscgis_pals$tableau_cat[["green"]]

myLfltGrey() %>% addPolygons(data = sea,color = green,opacity = 1,fillColor = green,fillOpacity = .5)

```

###King County Subdivision Boundary

```{r, echo=FALSE,warning=FALSE,message=FALSE}

if(!file.exists("./1_raw/seattle_ccd.gpkg")){
        tigris::county_subdivisions(state = "53",county = "033") %>% 
                subset(NAME == "Seattle") %>% 
                spTransform(CRSobj = crs_proj) %>% 
                writeOGR(dsn = "./1_raw/seattle_ccd.gpkg",
                         layer = "seattle", driver = "GPKG", verbose = FALSE, 
                         overwrite_layer = TRUE)
}

sea_ccd <- readOGR(dsn = "./1_raw/seattle_ccd.gpkg",layer = "seattle",verbose = FALSE)

orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]

myLfltGrey() %>% addPolygons(data = sea_ccd,color = orange,opacity = 1,fillColor = orange,fillOpacity = .5)

```

###Puget Sound Waterbodies

These are useful for "clipping" census geographies whose boundaries extend into waterbodies.

```{r}
library(downloader)


# check if the file already exists, if not then download it
if(!file.exists("./1_raw/NHDMajor.gdb")){
        
        url <- "ftp://www.ecy.wa.gov/gis_a/inlandWaters/NHD/NHDmajor.gdb.zip" # save the URL for the waterbodies data
        
        temp <- tempfile() # create a temporary file to hold the compressed download
        
        download(url, dest = temp, mode="wb") # download the file
        
        unzip (temp, exdir = "./1_raw/") # extract the ESRI geodatabase file to a project folder
}
                                
path_gdb <- "./1_raw/NHDMajor.gdb" # path to the geodatabase folder

wtr_sp <-
        readOGR(dsn = path_gdb,      # create a waterbodies shape
                layer = "NHD_MajorWaterbodies") %>%
        gBuffer(byid=TRUE, width=0) %>% # clean up self-intersecting polygons
        spTransform(CRSobj = crs_proj) # transform the projection to match the project projection

intersect <- gIntersects(sea_ccd,wtr_sp,byid = TRUE) %>% as.vector()

wtr_sp <- wtr_sp[intersect,] %>%
        spTransform(CRSobj = crs_proj)

blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]

myLfltGrey() %>% addPolygons(data = wtr_sp,color = blue, opacity = 1, weight = .5, fillColor = blue,fillOpacity = .5)

if(!file.exists("./2_intermediate/wtr_sp.gpkg")){
        writeOGR(obj = wtr_sp, dsn = "./2_intermediate/wtr_sp.gpkg", 
          layer = "wtr_sp", driver = "GPKG", verbose = FALSE, 
          overwrite_layer = TRUE)
}



```

