---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r vuln-lt-bach-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(leaflet.extras)
library(viridisLite)
library(sf)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
```

```{r vuln-lt-bach-colors}
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
proj_light_grey <- col2hex("grey75")
proj_grey <- col2hex("grey50")
proj_dark_grey <- col2hex("grey25")
```

### Educational Attainment: Low Formal Educational {-}
```{r vuln-lt-bach-acs, fig.cap= 'Adults 25+ With Less Than a Bachelor Degree (%), King County Census Tracts, 2010-2014'}

# Download the Census table for the project's geographies
# -----------------------------------------------------------------------------

if(!exists('coo_geo_acs')){coo_geo_acs <- read_rds(root_file('1-data/4-interim/coo-geo-acs.rds'))}

vuln_lt_bach_tbl <- "B15003"  # census table code

if(!file.exists(root_file('1-data/4-interim/vuln-lt-bach-orig-acs.rds'))){
        
        acs.fetch(endyear = 2014, geography = coo_geo_acs, 
                  table.number = vuln_lt_bach_tbl) %>%
                write_rds(root_file('1-data/4-interim/vuln-lt-bach-orig-acs.rds'))
        
}

vuln_lt_bach_orig_acs <- read_rds(root_file('1-data/4-interim/vuln-lt-bach-orig-acs.rds'))


# Process and save the data
# -----------------------------------------------------------------------------

if(!file.exists(root_file('1-data/4-interim/vuln-lt-bach-acs.rds'))){
        vuln_lt_bach_acs1 <- vuln_lt_bach_orig_acs
        
        vuln_lt_bach_tbl_guide <- 
                data.frame(terse = acs.colnames(vuln_lt_bach_acs1),
                           pretty = acs.colnames(acs.fetch(endyear = 2014, 
                                                           geography = geo.make(us = TRUE), 
                                                           table.number = vuln_lt_bach_tbl,col.names = 'pretty')))
        # Pull out the specific columns that are important
        
        get_col <- function(pattern){
                vuln_lt_bach_tbl_guide %>% filter(str_detect(pretty,pattern)) %>% select(terse) %>% unlist(use.names = FALSE) %>% as.character()
        }
        
        # Indicator universe total
        
        total <- get_col('Total:')
        
        vuln_lt_bach_total <- vuln_lt_bach_acs1[,total]
        
        acs.colnames(vuln_lt_bach_total) <- "ADULT_TOTAL_CNT"
        
        
        # Indicator count (All adults (25 y/o or older) with less that a BA)
        
        bach_plus <- get_col('Bachelor|Master|Professional|Doctorate')
        
        vuln_bach_plus <- 
                acs::apply(X = vuln_lt_bach_acs1[,bach_plus],
                           MARGIN = 2,
                           FUN = sum,
                           verbose = FALSE)
        
        acs.colnames(vuln_bach_plus) <- "BACH_PLUS"
        
        vuln_lt_bach <- vuln_lt_bach_total - vuln_bach_plus
        
        acs.colnames(vuln_lt_bach) <- "LT_BACH_CNT"
        
        
        # Share of adults with less than a BA
        
        vuln_lt_bach_pct <-  
                acs::apply(X = vuln_lt_bach,
                           MARGIN = 1,
                           FUN = divide.acs,
                           denominator = vuln_lt_bach_total,
                           method = "proportion",
                           verbose = FALSE)
        
        acs.colnames(vuln_lt_bach_pct) <- 'LT_BACH_PCT'
        
        # Combine the acs objects
        
        vuln_lt_bach_acs <- Reduce('cbind',c(vuln_lt_bach_pct,vuln_lt_bach,vuln_lt_bach_total))
        
        # Save the object
        
        vuln_lt_bach_acs %>% saveRDS(root_file('1-data/4-interim/vuln-lt-bach-acs.rds'))
}

vuln_lt_bach_acs <- read_rds(root_file('1-data/4-interim/vuln-lt-bach-acs.rds'))


# Plot the data
# -----------------------------------------------------------------------------

# Sanity check: the University of Washington Tract appears to have a very high margin of error (likely due to the small sample size), so it should be removed

vuln_lt_bach_noUW_acs <- vuln_lt_bach_ord_pct[standard.error(vuln_lt_bach_ord_pct)<.15,]

myAcsPlot(acs = vuln_lt_bach_noUW_acs,
          sort_fun = estimate,
          col = 'LT_BACH_PCT',
          ylab = 'Adults With Less Than a Bachelor Degree (%)',
          .pct = TRUE)

```

```{r vuln-lt-bach-sf}

if(!file.exists(root_file('1-data/4-interim/vuln-lt-bach-sf.rds'))){
        # Read in the `sf` object and re-order the records to by `JOIN_ID` 
        # -----------------------------------------------------------------------------

        if(!exists('coo_geos_sf')){coo_geos_sf <- read_rds(root_file('1-data/4-interim/coo-geos-sf.rds'))}        

        #
        # Convert the `acs` object into a dataframe, join to sf object
        # -----------------------------------------------------------------------------
        
        coo_vuln_lt_bach_sf <- 
                data.frame(
                        geography(vuln_lt_bach_acs)["NAME"],
                        geography(vuln_lt_bach_acs)["tract"],
                        estimate(vuln_lt_bach_acs), 
                        1.645 * standard.error(vuln_lt_bach_acs)) %>% 
                `colnames<-`(., c("NAME","GEOID6","LT_BACH_PCT_EST","LT_BACH_CNT_EST","ADULT_TOTAL_CNT_EST","LT_BACH_PCT_MOE","LT_BACH_CNT_MOE","ADULT_TOTAL_CNT_MOE")) %>% 
                mutate(JOIN_ID = case_when(.$NAME %in% 'King County, Washington' ~ 'KC',
                                           .$NAME %in% 'Seattle CCD, King County, Washington' ~ 'SEACCD',
                                           !is.na(.$GEOID6) ~ .$GEOID6)) %>%
                gather(VAR_TYPE,VALUE, matches('EST|MOE')) %>% 
                mutate(VAR = str_replace_all(VAR_TYPE,'_EST|_MOE',''),
                       TYPE = str_extract_all(VAR_TYPE,'EST|MOE',simplify = FALSE) %>% unlist(use.names = FALSE)) %>%
                spread(TYPE,VALUE) %>%
                arrange(NAME,VAR) %>%
                group_by(NAME,VAR) %>% 
                select(-VAR_TYPE) %>% 
                summarise_all(first_not_na) %>% 
                mutate(UPPER = EST + MOE,
                       LOWER = EST - MOE) %>%
                ungroup %>% 
                gather(TYPE,VAL,EST:LOWER) %>% 
                mutate(VAR_TYPE = paste(VAR,TYPE,sep = "_")) %>% 
                arrange(VAR_TYPE) %>% 
                spread(VAR_TYPE,VAL) %>% 
                group_by(NAME,VAR) %>% 
                summarise_all(first_not_na) %>% 
                ungroup %>% 
                select(-VAR,-TYPE) %>% 
                group_by(NAME) %>% 
                summarise_all(first_not_na) %>% 
                select(JOIN_ID,
                       matches('LT_BACH_PCT'),
                       matches('LT_BACH_CNT'),
                       everything(),
                       -NAME,-GEOID6) %>% as.data.frame() %>% 
                full_join(coo_geos_sf,by = 'JOIN_ID') %>% 
                st_sf()

#
# Save the object
# -----------------------------------------------------------------------------
coo_vuln_lt_bach_sf %>% write_rds(root_file('1-data/4-interim/vuln-lt-bach-sf.rds'))

}

coo_vuln_lt_bach_sf <-  read_rds(root_file('1-data/4-interim/vuln-lt-bach-sf.rds'))


```

##### Seattle CCD {-}
```{r vuln-lt-bach-seaccd-map}

tr <- 
        coo_vuln_lt_bach_sf %>% 
        filter(GEOGRAPHY == 'tract' & SEACCD_LGL)

seaccd_row <- which(coo_vuln_lt_bach_sf$JOIN_ID %in% 'SEACCD')[[1]]

my_pct <- function(x) round_any(x*100,1) %>% paste0("%")

popup_tbl_df <- 
        coo_vuln_lt_bach_sf %>% 
        mutate(LT_BACH_PCT_EST = my_pct(LT_BACH_PCT_EST),
               LT_BACH_CNT_EST = scales::comma(LT_BACH_CNT_EST),
               ADULT_TOTAL_CNT_EST = scales::comma(ADULT_TOTAL_CNT_EST)) %>% 
        select(-geometry) %>% 
        select('%' = LT_BACH_PCT_EST,
               '#' = LT_BACH_CNT_EST,
               '#' = ADULT_TOTAL_CNT_EST) %>% 
        as.data.frame(check.names = FALSE) %>% 
        `row.names<-`(coo_vuln_lt_bach_sf$JOIN_ID)

if(!file.exists(root_file('1-data/4-interim/vuln-lt-bach-seaccd-popup-tbl.rds'))){
        lapply(seq_along(1:nrow(popup_tbl_df)), 
               function(row) htmlTable::htmlTable(popup_tbl_df[c(row,seaccd_row),],
                                                  cgroup = c("No B.A.", "Adults"),n.cgroup = c(2,1)))[coo_vuln_lt_bach_sf$GEOGRAPHY %in% 'tract' & coo_vuln_lt_bach_sf$SEACCD_LGL] %>% 
                write_rds(root_file('1-data/4-interim/vuln-lt-bach-seaccd-popup-tbl.rds'))
}

if(!file.exists(root_file('1-data/4-interim/vuln-lt-bach-comm-popup-tbl.rds'))){
        lapply(seq_along(1:nrow(popup_tbl_df)), 
               function(row) htmlTable::htmlTable(popup_tbl_df[c(row,seaccd_row),],
                                                  cgroup = c("No B.A.", "Adults"),n.cgroup = c(2,1)))[coo_vuln_lt_bach_sf$GEOGRAPHY %in% 'tract' & coo_vuln_lt_bach_sf$SEACCD_LGL &!is.na(coo_vuln_lt_bach_sf$NAME)] %>% 
                write_rds(root_file('1-data/4-interim/vuln-lt-bach-comm-popup-tbl.rds'))
}

popup_tbl_seaccd <- read_rds(root_file('1-data/4-interim/vuln-lt-bach-seaccd-popup-tbl.rds'))

tr_comm <- 
        coo_vuln_lt_bach_sf %>% 
        filter(GEOGRAPHY == 'tract' & SEACCD_LGL &!is.na(NAME))

comm <- coo_vuln_lt_bach_sf %>% 
        filter(GEOGRAPHY == 'community')

comm_cntr <- comm %>% mutate(geometry = st_centroid(comm))

pal_lt_bach <- colorNumeric(viridis(256, option = "C"),tr$LT_BACH_PCT_EST)

comm_bounds <- comm %>% 
        as("Spatial") %>% 
        as("SpatialLines")

myLfltGrey() %>% 
        myLfltOpts() %>% 
        addPolygons(data = as(tr,'Spatial'),
                fillOpacity = .75,
                fillColor = ~pal_lt_bach(LT_BACH_PCT_EST),
                color = col2hex('white'),
                opacity = 1,
                weight = .5,
                smoothFactor = 0,
                popup = popup_tbl_seaccd) %>%
        addPolylines(data = comm_bounds,
                fillOpacity = 0,
                color = proj_dark_grey,
                opacity = 1,
                weight = 2,
                smoothFactor = 0) %>%
        addLabelOnlyMarkers(data = as(comm_cntr, "Spatial"),label = ~ NAME_FULL, labelOptions = labelOptions(noHide = TRUE,direction = 'left', textOnly = TRUE)) %>%  
        addLegend(title = "LESS THAN<br>BACH. DEGREE",
                  position = 'topright',
                  pal = pal_lt_bach, 
                  values = tr$LT_BACH_PCT_EST,
                  opacity = .75,
                  labFormat = labelFormat(suffix = '%',transform = function(x) 100 * x)) %>% 
        styleWidget(style = "text-transform:uppercase;text-shadow:-1px 0 #FFFFFF,0 1px #FFFFFF,1px 0 #FFFFFF,0 -1px #FFFFFF")

```
 
##### COO Communities {-}
```{r vuln-lt-bach-comm-map}

popup_tbl_comm <- read_rds(root_file('1-data/4-interim/vuln-lt-bach-comm-popup-tbl.rds'))

myLfltGrey() %>% 
        myLfltOpts() %>% 
        addPolygons(data = as(tr_comm,'Spatial'),
                fillOpacity = .75,
                fillColor = ~pal_lt_bach(LT_BACH_PCT_EST),
                color = col2hex('white'),
                opacity = 1,
                weight = .5,
                smoothFactor = 0,
                popup = popup_tbl_comm) %>%
        addPolylines(data = comm_bounds,
                fillOpacity = 0,
                color = proj_dark_grey,
                opacity = 1,
                weight = 2,
                smoothFactor = 0) %>%
        addLabelOnlyMarkers(data = as(comm_cntr, "Spatial"),label = ~ NAME_FULL, labelOptions = labelOptions(noHide = TRUE,direction = 'left', textOnly = TRUE)) %>% 
        addLegend(title = "LESS THAN<br>BACH. DEGREE",
                  position = 'topright',
                  pal = pal_lt_bach, 
                  values = tr$LT_BACH_PCT_EST,
                  opacity = .75,
                  labFormat = labelFormat(suffix = '%',transform = function(x) 100 * x)) %>% 
        styleWidget(style = "text-transform:uppercase;text-shadow:-1px 0 #FFFFFF,0 1px #FFFFFF,1px 0 #FFFFFF,0 -1px #FFFFFF")

```
