---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r typology-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(foreign)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(leaflet.extras)
library(viridisLite)
library(maptools)
library(cleangeo)
library(sf)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
```

### Introduction

```{r typology-colors}
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
proj_light_grey <- col2hex("grey75")
proj_grey <- col2hex("grey50")
proj_dark_grey <- col2hex("grey25")
```

_NOTE: this text is placeholder and must be changed_

### Combine Indicator Datasets

```{r typology-combine-inds}

# Load and join the indicator objects
# -----------------------------------------------------------------------------

# Load

coo_vuln_poc_sf <-  read_rds(root_file('1-data/4-interim/vuln-poc-sf.rds'))
coo_vuln_rent_sf <-  
        read_rds(root_file('1-data/4-interim/vuln-rent-sf.rds')) %>% 
        select(JOIN_ID,matches('RENT'))
coo_vuln_lt_bach_sf <-  read_rds(root_file('1-data/4-interim/vuln-lt-bach-sf.rds')) %>% 
        select(JOIN_ID,matches('BACH'))
coo_vuln_low_inc_sf <-  read_rds(root_file('1-data/4-interim/vuln-low-inc-sf.rds')) %>% 
        select(JOIN_ID,matches('LOW_INC'))

coo_chng_white_sf <-  read_rds(root_file('1-data/4-interim/chng-white-sf.rds'))%>% 
        select(JOIN_ID,matches('WHITE'))
coo_chng_own_sf <-  read_rds(root_file('1-data/4-interim/chng-own-sf.rds'))%>% 
        select(JOIN_ID,matches('OWN'))
coo_chng_bach_sf <-  read_rds(root_file('1-data/4-interim/chng-bach-sf.rds')) %>% 
        select(JOIN_ID,matches('BACH'))
coo_chng_inc_sf <-  read_rds(root_file('1-data/4-interim/chng-inc-sf.rds'))%>% 
        select(JOIN_ID,matches('INC'))

hous_tr_value_sf <- read_rds(root_file('1-data/4-interim/over-size-limit/hous-tr-value-sf.rds')) %>% 
         select(JOIN_ID,matches('TOTAL|UNIT'))

# Join

typology_inds_sf <- 
        coo_vuln_poc_sf %>% 
        full_join(coo_vuln_rent_sf,by = 'JOIN_ID') %>% 
        full_join(coo_vuln_lt_bach_sf,by = 'JOIN_ID') %>% 
        full_join(coo_vuln_low_inc_sf,by = 'JOIN_ID') %>% 
        full_join(coo_chng_white_sf,by = 'JOIN_ID') %>% 
        full_join(coo_chng_own_sf,by = 'JOIN_ID') %>% 
        full_join(coo_chng_bach_sf,by = 'JOIN_ID') %>% 
        full_join(coo_chng_inc_sf,by = 'JOIN_ID') %>% 
        full_join(hous_tr_value_sf,by = 'JOIN_ID') %>% 
        select(JOIN_ID,NAME:GEOG_FCT,everything(),geometry) %>% 
        st_as_sf() %>% 
        st_set_crs(crs_proj@projargs)

typology_inds_sf %>% arrange(desc(GEOG_FCT)) %>% print(10)

```


```{r typology-types}

seaccd <- function(x){typology_inds_sf[typology_inds_sf$NAME %in% 'SEACCD',x][[1]]}

exceeds_seaccd <- function(x, n){
        
        num_true <- x %>% which %>% length
        
        if(num_true >= n){TRUE}else{FALSE}
        
        }

typology <- 
        typology_inds_sf %>% 
        mutate(TYPO_VULN_RACE = case_when(.$POC_PCT_EST > seaccd('POC_PCT_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_VULN_RENT = case_when(.$RENT_PCT_EST > seaccd('RENT_PCT_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_VULN_LT_BACH = case_when(.$LT_BACH_PCT_EST > seaccd('LT_BACH_PCT_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_VULN_LOW_INC = case_when(.$LOW_INC_PCT_EST > seaccd('LOW_INC_PCT_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_CHNG_PCT_WHITE = case_when(.$CHNG_PCT_WHITE_EST > seaccd('CHNG_PCT_WHITE_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_CHNG_PCT_OWN = case_when(.$CHNG_PCT_OWN_EST > seaccd('CHNG_PCT_OWN_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_CHNG_PCT_BACH = case_when(.$CHNG_PCT_BACH_EST > seaccd('CHNG_PCT_BACH_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_CHNG_PCT_INC = case_when(.$CHNG_PCT_INC_EST > seaccd('CHNG_PCT_INC_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_CHNG_PCT_WHITE = case_when(.$CHNG_PCT_WHITE_EST > seaccd('CHNG_PCT_WHITE_EST') ~ TRUE,TRUE ~ FALSE),
               TYPO_HOUS_RATIO_2014 = round_any(TOTAL_VALUE_2014_MEDIAN/seaccd('TOTAL_VALUE_2014_MEDIAN'),.01),
               TYPO_HOUS_RATIO_2004 = round_any(TOTAL_VALUE_2004_MEDIAN/seaccd('TOTAL_VALUE_2004_MEDIAN'),.01),
               TYPO_HOUS_RATIO_1999 = round_any(TOTAL_VALUE_1999_MEDIAN/seaccd('TOTAL_VALUE_1999_MEDIAN'),.01),
               TYPO_HOUS_TYPE_2014 = ifelse(ntile(TYPO_HOUS_RATIO_2014,5) > 3,'HIGH','LOW'),
               TYPO_HOUS_TYPE_2004 = ifelse(ntile(TYPO_HOUS_RATIO_2004,5) > 3,'HIGH','LOW'),
               TYPO_HOUS_TYPE_1999 = ifelse(ntile(TYPO_HOUS_RATIO_1999,5) > 3,'HIGH','LOW'),
               TYPO_HOUS_APPR_99_04 = round_any(TOTAL_VALUE_2004_MEDIAN/TOTAL_VALUE_1999_MEDIAN,01),
               TYPO_HOUS_APPR_99_04_TYPE = ifelse(ntile(TYPO_HOUS_APPR_99_04,5) > 3,'HIGH','LOW'),
               TYPO_HOUS_APPR_04_14 = round_any(TOTAL_VALUE_2014_MEDIAN/TOTAL_VALUE_2004_MEDIAN,01),
               TYPO_HOUS_APPR_04_14_TYPE = ifelse(ntile(TYPO_HOUS_APPR_04_14,5) > 3,'HIGH','LOW'),
               TYPO_HOUS_APPR_99_14 = round_any(TOTAL_VALUE_2014_MEDIAN/TOTAL_VALUE_1999_MEDIAN,01),
               TYPO_HOUS_APPR_99_14_TYPE = ifelse(ntile(TYPO_HOUS_APPR_99_14,5) > 3,'HIGH','LOW') 
        )
                       
typo_vuln <- 
        typology %>% 
        gather(VULN_IND,VULN_LGL,matches('TYPO_VULN')) %>% 
        group_by(JOIN_ID) %>%
        summarise(VULN_LGL = exceeds_seaccd(VULN_LGL,3)) %>% 
        left_join(typology,.,by = 'JOIN_ID')

typo_chng <- 
        typo_vuln %>% 
        gather(CHNG_IND,CHNG_LGL,matches('TYPO_CHNG')) %>% 
        group_by(JOIN_ID) %>%
        summarise(CHNG_LGL = exceeds_seaccd(CHNG_LGL,2)) %>% 
        left_join(typo_vuln,.,by = 'JOIN_ID') %>% 
        st_as_sf() %>% 
        rename(geometry = geometry.x)
               
               
# Neighbors

sp <- as(typology,'Spatial')

sp_1 <- SpatialPolygons(sp@polygons)

nb_1 <- poly2nb(sp_1)

near_high <- lapply(nb_1,function(x){typology[x,"TYPO_HOUS_TYPE_2014"][[1]] %in% 'HIGH' | typology[x,"TYPO_HOUS_APPR_04_14_TYPE"][[1]] %in% 'HIGH'})

any_near_high <- lapply(near_high,any) %>% unlist

# Housing Market (all three indicators)

typo_hous <- 
        typo_chng %>% 
        mutate(TYPO_HOUS_APPR = ifelse(TYPO_HOUS_TYPE_1999 %in% 'LOW' & TYPO_HOUS_TYPE_2014 %in% 'HIGH' & TYPO_HOUS_APPR_99_14_TYPE %in% 'HIGH',TRUE,FALSE),
               TYPO_HOUS_ACCL = ifelse(TYPO_HOUS_TYPE_2014 %in% 'HIGH' & TYPO_HOUS_APPR_04_14_TYPE %in% 'HIGH',TRUE,FALSE),
               TYPO_HOUS_ADJ_NEAR = any_near_high,
               TYPO_HOUS_ADJ = ifelse(TYPO_HOUS_TYPE_2014 %in% 'LOW' & TYPO_HOUS_APPR_04_14_TYPE %in% 'LOW' & TYPO_HOUS_ADJ_NEAR,TRUE,FALSE)
               )



# Typologies

typo_types <- 
        typo_hous %>% 
        mutate(TYPO_TYPE = ifelse(VULN_LGL & CHNG_LGL %!in% TRUE & TYPO_HOUS_ADJ,
                                  'Susceptible',
                                  ifelse(VULN_LGL & CHNG_LGL %!in% TRUE & TYPO_HOUS_ACCL,
                                         'Early Type 1',
                                         ifelse(VULN_LGL & CHNG_LGL & TYPO_HOUS_ADJ,
                                               'Early Type 2',
                                                ifelse(VULN_LGL & CHNG_LGL & TYPO_HOUS_ACCL,
                                                       'Dynamic',
                                                       ifelse(VULN_LGL & CHNG_LGL & TYPO_HOUS_APPR,
                                                              'Late',
                                                              ifelse(VULN_LGL %!in% TRUE & CHNG_LGL & TYPO_HOUS_APPR,
                                                                     'Continued Loss',NA)))))))


typo_types_ord <-
        typo_types %>% 
        mutate(TYPO_TYPE_FCT = factor(TYPO_TYPE,
                                      levels = c('Susceptible',
                                                 'Early Type 1',
                                                 'Early Type 2',
                                                 'Dynamic',
                                                 'Late',
                                                 'Continued Loss'),ordered = TRUE)) %>% 
        st_as_sf()


# typo_types_ord %>% 
#         mutate_if(is.factor,.funs = as.character) %>% 
#         as('Spatial') %>% 
#         writeOGR(dsn = '.',layer = 'typology',driver = 'ESRI Shapefile',verbose = FALSE)


```




