---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r condo-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(foreign)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(leaflet.extras)
library(viridisLite)
library(maptools)
library(cleangeo)
library(sf)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
```

### Introduction

```{r condo-colors}
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
proj_light_grey <- col2hex("grey75")
proj_grey <- col2hex("grey50")
proj_dark_grey <- col2hex("grey25")
```

_NOTE: this page is unfinished work_


### Condo Metadata

```{r condo-meta-2014}

# Set the file path to the geodatabase

fp_2014 <- root_file('1-data/3-external/manual/over-size-limit/Year2015.gdb/')


# Value and Property Type Metadata
# -----------------------------------------------------------------------------

# Read in value data and prop type data

prcl_value_clean_2014 <- read_rds(root_file('1-data/4-interim/over-size-limit/prcl-value-clean-2014.csv'))

prcl_type_2014 <- read_csv(root_file('1-data/4-interim/over-size-limit/prcl-type-2014.csv'),
                         col_types = cols_only(PIN = 'c',PROPTYPE = 'c'),
                         progress = FALSE)

# Condo Complex and Condo Unit Metadata
# -----------------------------------------------------------------------------


# Read in the condo units data

if(!file.exists(root_file('1-data/4-interim/over-size-limit/prcl-condo-units-2014.csv'))){
        layers <- ogrListLayers(fp_2014)

        layers[1:length(layers)]

        fp_prop_condo_units_2014 <- root_file('1-data/4-interim/over-size-limit/prcl-condo-units-2014.csv')

        ogr_cmd <- paste("ogr2ogr -f CSV",fp_prop_condo_units_2014,fp_2014,'CONDOUNIT_EXTR',sep = ' ')

        system(ogr_cmd)
}

prcl_condo_units_2014 <- read_csv(root_file('1-data/4-interim/over-size-limit/prcl-condo-units-2014.csv'),
                         col_types = cols_only(PIN = 'c',UNITTYPE = 'c'),
                         progress = FALSE)


# Read in the condo complex data

if(!file.exists(root_file('1-data/4-interim/over-size-limit/prcl-condo-2014.csv'))){
        layers <- ogrListLayers(fp_2014)

        layers[1:length(layers)]

        fp_prop_condo_2014 <- root_file('1-data/4-interim/over-size-limit/prcl-condo-2014.csv')

        ogr_cmd <- paste("ogr2ogr -f CSV",fp_prop_condo_2014,fp_2014,'CONDOCOMPLEX_EXTR',sep = ' ')

        system(ogr_cmd)
}

prcl_condo_2014 <- read_csv(root_file('1-data/4-interim/over-size-limit/prcl-condo-2014.csv'),
                         col_types = cols_only(PIN = 'c',COMPLEXTYPE = 'c', NBRUNITS = 'i'),
                         progress = FALSE)
```

```{r}



```

