---
df_print: tibble
output:
  html_notebook:
    code_folding: hide
  pdf_document:
    keep_tex: yes
always_allow_html: yes
---

```{r typology-setup, echo = FALSE, warning=FALSE,message=FALSE,comment=FALSE}
library(plyr)
library(knitr)
library(rprojroot)
library(rgdal)
library(sp)
library(rgeos)
library(tigris)
library(leaflet)
library(foreign)
library(ggthemes)
library(magrittr)
library(stringr)
library(downloader)
library(webshot)
library(htmltools)
library(gplots)
library(ggmap)
library(shiny)
library(htmlwidgets)
library(readxl)
library(acs)
library(RColorBrewer)
library(forcats)
library(tidyverse)
library(miscgis)
library(operator.tools)
library(leaflet.extras)
library(viridisLite)
library(maptools) 
library(sf)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE, comment=FALSE)
```


```{r typology-colors}
green <- miscgis::miscgis_pals$tableau_cat[["green"]]
blue <- miscgis::miscgis_pals$tableau_cat[["blue"]]
orange <- miscgis::miscgis_pals$tableau_cat[["orange"]]
red <- miscgis::miscgis_pals$tableau_cat[["red"]]
teal <- miscgis::miscgis_pals$tableau_cat[["teal"]]
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_4 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
pal_rgb_6 <- miscgis::miscgis_pals$tableau_cat[c("red","gold","green","blue","orange","purple")] %>% unlist %>% palette()
proj_light_grey <- col2hex("grey75")
proj_grey <- col2hex("grey50")
proj_dark_grey <- col2hex("grey25")
```


```{r typology-combine-inds}

typology_sf <- read_rds(root_file('1-data/5-tidy/typology.rds'))


my_pal <- c(
        RColorBrewer::brewer.pal(n = 9,'YlOrRd')[c(3,5,6)],
        RColorBrewer::brewer.pal(n = 9,'RdPu')[c(6)],
        RColorBrewer::brewer.pal(n = 9,'YlGnBu')[c(6,7)]
)

pal <- colorFactor(my_pal,levels = levels(typology_sf$TYPO_TYPE_KC_FCT), ordered = TRUE,na.color = 'transparent')

vals <- levels(ordered(typology_sf$TYPO_TYPE_KC_FCT))

typology_sf %>% 
        filter(GEOGRAPHY %in% 'tract') %>% 
        myLfltGrey() %>% 
        myLfltOpts() %>%  
        addPolygons(fillColor = ~pal(TYPO_TYPE_KC_FCT), fillOpacity = .75, smoothFactor = 0,
                    color = 'white', opacity = .85, weight = .5,
                    popup = ~JOIN_ID) %>%
        addLegend(title = '',position = 'topright',pal = pal, values = ~TYPO_TYPE_KC_FCT, opacity = .75)




```
