# (APPENDIX) Appendices {-}

```{r data-methods-setup, echo=FALSE, warning=FALSE, message=FALSE}
library(knitr)
library(rprojroot)
library(tidyverse)
root <- rprojroot::is_rstudio_project
root_file <- root$make_fix_file()
opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
options("readr.num_columns" = 0)
```

# Data Methods

## Miscellaneous
```{r data-methods-misc}
misc_fp <- root_file('1-data/1-notebooks/01-misc.Rmd')
```

`r knit_child(misc_fp)`

## Census Data

```{r data-methods-census}

census_acs_fp <- root_file('1-data/1-notebooks/02-census-acs.Rmd')

census_acs_comms_fp <- root_file('1-data/1-notebooks/02-census-acs-communities.Rmd')

```

`r knit_child(census_acs_fp)`
`r knit_child(census_acs_comms_fp)`

## King County Assessor Data

```{r data-methods-kc-parcels}
# kc_parcels_fp <- root_file('1-data/1-notebooks/02-king-county-parcels.Rmd')
```


## Indicators

```{r data-methods-indicators}

make_acs_inds_fp <- root_file('1-data/1-notebooks/03-make-acs-inds.Rmd')

make_acs_maps_fp <- root_file('1-data/1-notebooks/03-make-acs-maps.Rmd')

ind_intro_fp <- root_file('1-data/1-notebooks/03-indicators-intro.Rmd')

vuln_intro_fp <- root_file('1-data/1-notebooks/03-vuln-intro.Rmd')

vuln_poc_fp <- root_file('1-data/1-notebooks/03-vuln-poc.Rmd')

vuln_rent_fp <- root_file('1-data/1-notebooks/03-vuln-rent.Rmd')

vuln_lt_bach_fp <- root_file('1-data/1-notebooks/03-vuln-lt-bach.Rmd')

vuln_low_inc_fp <- root_file('1-data/1-notebooks/03-vuln-low-inc.Rmd')

demo_chng_intro_fp <- root_file('1-data/1-notebooks/03-demo-change-intro.Rmd')

demo_chng_white_fp <- root_file('1-data/1-notebooks/03-demo-change-white.Rmd')

demo_chng_own_fp <- root_file('1-data/1-notebooks/03-demo-change-own.Rmd')

demo_chng_bach_fp <- root_file('1-data/1-notebooks/03-demo-change-bach.Rmd')

demo_chng_income_fp <- root_file('1-data/1-notebooks/03-demo-change-inc.Rmd')

test_crosstalk_fp <- root_file('1-data/1-notebooks/tmp/tmp-crosstalk-test.Rmd')
```

`r knit_child(ind_intro_fp)`
`r knit_child(make_acs_inds_fp)`
`r knit_child(make_acs_maps_fp)`
`r knit_child(vuln_intro_fp)`
`r knit_child(vuln_poc_fp)`
`r knit_child(test_crosstalk_fp)`

## Typology